image: docker:latest

stages:
  - build
  - update

# This file is a template, and might need editing before it works on your project.
push to docker hub:
  # Official docker image.
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_USER/$CI_PROJECT_NAME:latest" -t "$CI_REGISTRY_USER/$CI_PROJECT_NAME:1.$CI_PIPELINE_ID" .
    - docker push "$CI_REGISTRY_USER/$CI_PROJECT_NAME"
    - docker image rm "$CI_REGISTRY_USER/$CI_PROJECT_NAME:latest"

  only:
    - master

test build:
  # Official docker image.
  image: docker:latest
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_USER/$CI_PROJECT_NAME:test" .
  except:
    - master
