version: '3.1'

services:
  ranksystem:
    image: capdeveloping/teamspeak-3-ranksystem:1.2
    container_name: teamspeak_ranksystem
    restart: always
    environment:
      SUBPATH: true (optional - default value)
      SUBFOLDER: "ranksystem" (optional - default value)
      CRONTIMES: "*/10 * * * *" (optional - default value)
    ports:
      - 8088:80
    volumes:
      - /path/to/folder/dbconfig.php:/var/www/html/ranksystem/other/dbconfig.php
networks:
    teamspeak-network:
        driver: bridge
