version: '3.1'

services:
  ranksystem:
    image: kourgiantakis/docker-teamspeak-ranksystem
    container_name: teamspeak_ranksystem
    restart: always
    ports:
      - 8088:80
    volumes:
      - ./dbconfig.php:/var/www/html/ranksystem/other/dbconfig.php
    networks:
      teamspeak-network:

networks:
    teamspeak-network:
        driver: bridge
